DEFRA/adp-aso-helm-library

README.md
adp-aso-helm-library/.helmignore
adp-aso-helm-library/Chart.yaml
adp-aso-helm-library/templates/_helpers.tpl
adp-aso-helm-library/templates/_utils.yaml

ASO Library Initial setup and Helper functions
AB#244987

244987 ASO Library Initial setup and Helper functions

---

README.md
adp-aso-helm-library/templates/_namespace-queue.yaml
adp-aso-helm-library/templates/_namespacesqueue.yaml

This PR contains the changes to add a template for Service bus Namespacesqueue 
AB#244986

244986: ServiceBus Namespacesqueue template

---

README.md
adp-aso-helm-library/templates/_namespace-queue.yaml
adp-aso-helm-library/templates/_namespace-topic-subscription-rule.yaml
adp-aso-helm-library/templates/_namespace-topic-subscription.yaml
adp-aso-helm-library/templates/_namespace-topic.yaml

Added ASO library templates for below,
- NamespacesTopic
- NamespacesTopicsSubscription
- NamespacesTopicsSubscriptionsRule
Also updated readme documentation
AB#247169

247169: NamespacesTopic and Child templates

---

README.md
adp-aso-helm-library/templates/_federated-credential.yaml
adp-aso-helm-library/templates/_flexible-servers-db.yaml
adp-aso-helm-library/templates/_helpers.tpl
adp-aso-helm-library/templates/_role-assignment.yaml
adp-aso-helm-library/templates/_userassignedidentity.yaml

AB#246045 
- Manage Identity
- Fed creds
- Role assignments
readme is pending and will update in another PR

246045 : Identity templates

---

.azuredevops/publish-helm-library.yaml
adp-aso-helm-library/Chart.yaml

Pipeline to publish ASO Helm Library to Shared ACR
[AB#250126](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/250126)
Pipeline run to validates and publish helm library.
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=382942&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9

250126: Pipeline to publish ASO Helm Library to Shared ACR

---

README.md
adp-aso-helm-library/templates/_namespace-topic.yaml

Updated template to support independent topic subscription creation

254838: Updated template to support independent topic subscription creation

---

README.md
adp-aso-helm-library/Chart.yaml
adp-aso-helm-library/templates/_federated-credential.yaml
adp-aso-helm-library/templates/_role-assignment.yaml
adp-aso-helm-library/templates/_userassignedidentity.yaml

**Description:**
- Update userAssignedIdentity template to support multiple fedcred creation
- Updated pending readme documentation
AB#250126

250126:  Readme update for MI and Roleassignment templates

---

README.md
adp-aso-helm-library/Chart.yaml
adp-aso-helm-library/templates/_federated-credential.yaml
adp-aso-helm-library/templates/_role-assignment.yaml
adp-aso-helm-library/templates/_userassignedidentity.yaml

ASO MI template upgraded to use platform variables

258122: ASO MI template upgrades to use platform variables

---

.azuredevops/publish-helm-library.yaml
adp-aso-helm-library/Chart.yaml
adp-aso-helm-library/templates/_federated-credential.yaml
adp-aso-helm-library/templates/_role-assignment.yaml
adp-aso-helm-library/templates/_userassignedidentity.yaml

258122 : MI templates upgrades

---

README.md
adp-aso-helm-library/Chart.yaml
adp-aso-helm-library/templates/_built-in-roles.tpl
adp-aso-helm-library/templates/_flexible-servers-db.yaml
adp-aso-helm-library/templates/_helpers.tpl
adp-aso-helm-library/templates/_keyvault-secrets-role-assignment.yaml
adp-aso-helm-library/templates/_namespace-queue.yaml
adp-aso-helm-library/templates/_namespace-topic.yaml
adp-aso-helm-library/templates/_userassignedidentity.yaml
pull_request_template.md

- Added Keyvault secret RBAC template
- Platform variables abstraction from the users values.yaml (user can supply while doing local testing)
- No need to supply empty "userAssignedIdentity: {}" in users value.yaml file
- Readme documentation update
AB#261143

261143: ASO Keyvault secret RBAC template and platform variables abstraction

---

adp-aso-helm-library/Chart.yaml
adp-aso-helm-library/templates/_userassignedidentity.yaml

*Added fix for userassignedidentity template for default location*
*Simplified if conditions*
*[AB#262177](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/262177)*
n/a
n/a

262177: Added fix for userassignedidentity template for default location

---

README.md
adp-aso-helm-library/Chart.yaml
adp-aso-helm-library/templates/_helpers.tpl
adp-aso-helm-library/templates/_keyvault-secrets-role-assignment.yaml
adp-aso-helm-library/templates/_role-assignment-managed.yaml

RBAC name fix to make it unique name.
[AB#261143](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/261143)

261143: RBAC name fix

---

README.md
adp-aso-helm-library/Chart.yaml
adp-aso-helm-library/templates/_federated-credential.yaml
adp-aso-helm-library/templates/_role-assignment.yaml
adp-aso-helm-library/templates/_service-account.yaml
adp-aso-helm-library/templates/_workload-identity.yaml

*Added service account template for workload identity*
*Updated UserAssignedManagedIdentity template to use ServiceAccount and updated the template name to workload identity*
*Updated README to reflect all changes*
*[AB#262177](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/262177)*
*
*

262177: Updated to create a service account and workload identity

---

adp-aso-helm-library/Chart.yaml
adp-aso-helm-library/templates/_helpers.tpl

Change the config map name to be more readable
Relates to ADO Work Item [AB#262177](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/262177)
N/A
N/A

262177: Config map name change

---

adp-aso-helm-library/Chart.yaml
adp-aso-helm-library/templates/_namespace-topic-subscription-rule.yaml
adp-aso-helm-library/templates/_namespace-topic-subscription.yaml

ASO TopicSubscription and TopicSubscriptionRule name updated to make it unique
Relates to ADO Work Item [AB#262177](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/262177)

262177 : Topic subscription and rule name updated to make it unique

---

README.md
adp-aso-helm-library/Chart.yaml
adp-aso-helm-library/templates/_built-in-roles.tpl
adp-aso-helm-library/templates/_helpers.tpl
adp-aso-helm-library/templates/_storage-account-blob-service.yaml
adp-aso-helm-library/templates/_storage-account-blob-services-container.yaml
adp-aso-helm-library/templates/_storage-account-role-assignment.yaml
adp-aso-helm-library/templates/_storage-account-table-services-table.yaml
adp-aso-helm-library/templates/_storage-account.yaml

```
Added support for Storage Helm template
- Creates storage account
- Blob and RBAC
- Table and RBAC
- Documentation with examples
```
Relates to ADO Work Item [AB#292526](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/292526)
[*Any relevant testing information and pipeline runs.*](https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=466511&view=results)

292526:  Storage Helm template with Blob, Table and RBAC support 

---

README.md
adp-aso-helm-library/Chart.yaml
adp-aso-helm-library/templates/_built-in-roles.tpl
adp-aso-helm-library/templates/_helpers.tpl
adp-aso-helm-library/templates/_storage-account-blob-service.yaml
adp-aso-helm-library/templates/_storage-account-blob-services-container.yaml
adp-aso-helm-library/templates/_storage-account-private-endpoint.yaml
adp-aso-helm-library/templates/_storage-account-table-services-table.yaml
adp-aso-helm-library/templates/_storage-account.yaml

- Added Storage account Private Endpoint template
- Added feature flag for PrivateEndpointsPrivateDnsZoneGroup
- readme documentation update
Relates to ADO Work Item [AB#306948](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/306948)
We are currently awaiting the design for the private DNS zone. @kbabigumira  will follow up with Mike on this. The current setup only creates a private endpoint on the storage account but does not add an A record in the DNS zone. cc: @DaRoszko 

306948 : Private endpoint for storage account

---

adp-aso-helm-library/Chart.yaml
adp-aso-helm-library/templates/_flexible-servers-db.yaml
adp-aso-helm-library/templates/_storage-account-blob-service.yaml
adp-aso-helm-library/templates/_storage-account-blob-services-container.yaml
adp-aso-helm-library/templates/_storage-account-table-services-table.yaml
adp-aso-helm-library/templates/_storage-account.yaml

Updated key data resources to ensure that ASO does not delete the resource if the CRD is deleted from the cluster.
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#381518](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/381518)

381518: Added reconcile-policy to prevent deletion of Azure resources

---

adp-aso-helm-library/Chart.yaml
adp-aso-helm-library/templates/_storage-account.yaml

Configure the storage public access based on flag.
N/A
N/A

Configure the storage public access based on flag.

---

adp-aso-helm-library-test/.helmignore
adp-aso-helm-library-test/Chart.lock
adp-aso-helm-library-test/Chart.yaml
adp-aso-helm-library-test/templates/namespace-queue.yaml
adp-aso-helm-library-test/templates/namespace-topic.yaml
adp-aso-helm-library-test/templates/storage-account.yaml
adp-aso-helm-library-test/values.yaml
adp-aso-helm-library/Chart.yaml

Added a test chart. Can be used to implement unit tets.

Added a test chart for ASO helm charts

---

README.md
adp-aso-helm-library-test/Chart.yaml
adp-aso-helm-library-test/values.yaml
adp-aso-helm-library/Chart.yaml
adp-aso-helm-library/templates/_helpers.tpl
adp-aso-helm-library/templates/_storage-account-file-service.yaml
adp-aso-helm-library/templates/_storage-account-file-services-share.yaml
adp-aso-helm-library/templates/_storage-account.yaml

Add support for the File Share creation on storage accounts
Relates to ADO Work Item [AB#383639](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/383639)
N/A
N/A

383639: Add support for the File Share creation on storage accounts

---

README.md
adp-aso-helm-library/Chart.yaml
adp-aso-helm-library/templates/_storage-account.yaml

- Allow Services in the team to create RBAC on existing Storage account
Relates to ADO Work Item [AB#383700](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/383700) 
Below is the test:
**sndadpinfst3401nceasrh** storage account is created by Harvester service.
**Enricher** and **Mapper** service needs DataWriter and DataReader access respectively.

383700: Allow Services in the team to create RBAC on existing Storage account
